### ISSUE TITLE
Some storage types cause container to infinitely stall

### ISSUE THREAD

**Issue by Macrofarad** [linuxserver/docker-wikijs#16] opened 2022-01-31 20:55 UTC
### Preface
I'm bundling these two bugs together as I suspect they may be related.

### Logs from Git storage type stall:

......
2022-01-31T20:38:02.625Z [MASTER] [32minfo[39m: Syncing with storage target git...
2022-01-31T20:38:02.635Z [MASTER] [32minfo[39m: (STORAGE/GIT) Performing push to origin on branch origin...
2022-01-31T20:38:03.434Z [MASTER] [32minfo[39m: Syncing with storage target git: [ COMPLETED ]
(node:304) TimeoutOverflowWarning: 63072300000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
2022-01-31T20:38:03.452Z [MASTER] [32minfo[39m: Syncing with storage target git...
2022-01-31T20:38:03.462Z [MASTER] [32minfo[39m: (STORAGE/GIT) Performing push to origin on branch origin...
2022-01-31T20:38:03.612Z [MASTER] [32minfo[39m: (STORAGE/DISK) Initializing...
2022-01-31T20:38:03.612Z [MASTER] [32minfo[39m: (STORAGE/DISK) Initialization completed.
2022-01-31T20:38:03.434Z [MASTER] [32minfo[39m: Syncing with storage target git: [ COMPLETED ]
(node:304) TimeoutOverflowWarning: 63072300000 does not fit into a 32-bit signed integer.
......

### Steps to reproduce Git storage stall: 
Enable Git storage, set it up, try to sync.

### Logs from Local storage type stall:

2022-01-31T20:47:10.099Z [MASTER] [32minfo[39m: (STORAGE/DISK) Dumping all content to disk...
2022-01-31T20:48:10.114Z [MASTER] [33mwarn[39m: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

### Steps to reproduce Git storage stall: 
Attempt to dump all content to disk.

### Notes

Either of these conditions will cause the container to stall until the container is reset.   If someone set the git sync timer to a low enough time frame, it could even cause the entire container to become unusable.  Goes without saying, but thank you for all your hard work.

**Comment by RyMaxim** [comment] 2022-04-04 15:26
@Macrofarad I had this same issue and went digging today to sort it out. The issue seems to be caused by the default single database connection. This can be changed in `config.yml`.

1. Open `<path to config>/config.yml` (you defined this in your `docker run` command)
2. Scroll down to "Database Pool Options"
3. Un-comment the `min` and `max` values for the `pool:` setting (line 90 for me). You may want to tweak these dependent on your hardware. I left the default values of `min: 2` and `max: 10` in place
5. Save the file
6. Restart the container to reload the config (not sure if this is necessary)

After this change, both the Git and LFS storage modules were able to dump my wiki to disk without errors.

**Comment by lostwindsenril** [comment] 2022-12-11 13:14
> @Macrofarad I had this same issue and went digging today to sort it out. The issue seems to be caused by the default single database connection. This can be changed in `config.yml`.
> 
> 1. Open `<path to config>/config.yml` (you defined this in your `docker run` command)
> 2. Scroll down to "Database Pool Options"
> 3. Un-comment the `min` and `max` values for the `pool:` setting (line 90 for me). You may want to tweak these dependent on your hardware. I left the default values of `min: 2` and `max: 10` in place
> 4. Save the file
> 5. Restart the container to reload the config (not sure if this is necessary)
> 
> After this change, both the Git and LFS storage modules were able to dump my wiki to disk without errors.

This solved my problem, thank you!

**Comment by lostwindsenril** [comment] 2022-12-11 13:23
It's hard to believe that eight months have passed and no action has been taken by the mirror's maintainers. No longer trust Linuxserver images.

**Comment by lostwindsenril** [comment] 2022-12-11 13:24
It's hard to believe that eight months have passed and no action has been taken by the maintainers. No longer trust Linuxserver images.

**Comment by gawainXX** [comment] 2022-12-11 18:55
> It's hard to believe that eight months have passed and no action has been taken by the maintainers. No longer trust Linuxserver images.

I'm feeling the same way, may just build a VM to run it old school style. props to @RyMaxim  though.

**Comment by drizuid** [comment] 2023-03-21 12:26
issue template was not fully filled out in a timely manner. closing.

**Closed as not planned by drizuid** 2023-03-21 12:26 UTC
Labels: no-issue-activity
